
# # Specify compiler
# CC=gcc

# # Specify linker
# LINK=gcc

# .PHONY : all
# all : app# Link the object files into a binary


# tic : tic.out
#     $(LINK) -o tic tic.out -lstdc++# Compile the source files into object files


# tic.out : game.cpp gamemodes.cpp gui.cpp main.cpp minimax.cpp
#     $(CC) -c game.cpp gamemodes.cpp gui.cpp main.cpp minimax.cpp -o main.o
# .PHONY : clean
# # Clean target

# clean :
#     rm tic.out tic

